config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'welcome/index'
  get  'forms/new'
  get 'forms/index'
  get 'forms/log'
  get 'forms/create'
  get 'users/new'
  get    '/signup',  to: 'forms#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  post '/users' =>'users#create'
  delete '/logout',  to: 'sessions#destroy'
  get '/form/logged_in', to: 'sessions#logged_in'
  get "/sessions/logout", to: 'sessions#logout'
get '/layouts/header',to: 'forms#create'
  resources :forms

resources :session
root 'welcome#index'
root 'forms#log'
  root 'users#new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

end

app/models/form.rb
class Form < ApplicationRecord

  validates :firstname,length: { minimum: 2 },:format => { :with => /\A[a-zA-Z]+\z/, :message => "Only letters allowed" }
  validates  :lastname,length: { minimum: 2 }
  validates :address, length: { minimum: 4 }
validates_presence_of :password, length: { minimum: 6 }


  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX } , length: { minimum: 6}
  validates_uniqueness_of :email




end

app/models/session.rb
class Session < ApplicationRecord
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX } , length: { minimum: 6},:message=>"invalid"
  validates_uniqueness_of :email
  validate :password
end

app/models/user.rb
class User < ApplicationRecord
  validates :email,:password, presence:true
  has_secure_password
  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email, :on => :create
  validates_presence_of :firstname,length: { minimum: 2 },:format => { :with => /\A[a-zA-Z]+\z/, :message => "Only letters allowed" }
  validates_presence_of :lastname,length: { minimum: 2 }
  validates_presence_of :address, length: { minimum: 4 }
  validates_presence_of :password, length: { minimum: 6 }



  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX } , length: { minimum: 6}
  validates_uniqueness_of :email

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  add_flash_types :notice, :another_custom_type
  protect_from_forgery with: :exception
  include SessionsHelper
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def authorize
    redirect_to '/login' unless current_user
  end

end

app/controllers/forms_controller.rb
class FormsController < ApplicationController
		

def index
@form=Form.all
end



def new
@form=Form.new

end

def show 
@form=Form.find(params[:id])
end


def create
  @form=Form.new(form_params)
  if @form.save
    flash[:notice]="Successfully signed up"

    redirect_to '/forms/new'
  else
    #flash[:notice]="**Fields cant be blank"

    render 'new',flash[:notice]=>"fields cant b empty"
  end
end


def form_params
 params.require(:form).permit(:firstname,:lastname,:email,:password,:address)
end

def destroy

end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    if session[:user_id]
      @user=Form.find session[:user_id]
      render :template => "sessions/logged_in"
    else

      render :template => "sessions/new"
    end
  end
  def create
    if params[:email] and params[:password]
      @user = Form.where('email =? and password =?',params[:email],params[:password]).first
      logger.info "========i am here==#{@user.inspect}"
      if @user.blank?
        flash[:notice]="**Email and password fields cannot be empty"
        redirect_to "/login"
      else

        session[:user_id] = @user.id
        #redirect_to logged_in_users_path(:id=>@user.id)
        render :template => "sessions/logged_in"
      end

    end
 end


  def logged_in
    render :template => "/session/logged_in"
  end

  def logout
    session[:user_id] = nil
    redirect_to "/forms/new"
  end




      def destroy
        session[:user_id]=user.id
            redirect_to '/session/login',:notice=>"loggedout "
      end
  end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
@user=User.all
  end
  def create

    @user=User.new(user_params)
    if @user.save
      flash[:notice]="Successfully signed up"

      redirect_to '/users/new'
    else
      #flash[:notice]="**Fields cant be blank"

      render 'new',flash[:notice]=>"fields cant b empty"
    end


end

  def user_params
    params.require(:user).permit(:name,:email,:password,:password_confirmation)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/forms_helper.rb
module FormsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(form)
    session[:form_id] = form.id
  end
  def current_user
    @current_user ||= Form.find_by(id: session[:user_id])
  end
  def logged_in?
    !current_user.nil?
  end
  def authenticate

  end
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/forms/index.html.erb
<body style="background-color:pink;">
<style>



  table {
    font-family: arial, sans-serif;
    border-collapse: collapse;
    width: 100%;
  }


  td, th {
    border: 1px solid blueviolet;
    text-align: left;
    padding: 8px;
  }

  tr:nth-child(even) {
    background-color: darkgrey;
  }
</style>
</body>
<h1 style="color:darkred;">Listing of Members</h1>


<table>
  <tr>
    <th>Firstname</th>
    <th>Lastname</th>
    <th>Email</th>
    <th>password</th>
    <th>Address</th>

  </tr>


  <% @form.each do |form| %>
      <tr>
        <td><%= form.firstname %></td>
        <td><%= form.lastname %></td>
        <td><%= form.email %></td>
        <td><%= form.password %></td>
        <td><%= form.address %></td>
        <td><%= link_to 'Show', form_path(form) %></td>
      </tr>
  <% end %> <br>
  <%= link_to 'New Entry', new_form_path %><br><br><br>

</table>

app/views/forms/log.html.erb
<%= form_for :form, url: forms_path do |f| %>
  <div class="container">
    <h1><%= link_to "Form", root_path, id: "logo" %></h1>
    <nav>
      <ul class="nav navbar-nav navbar-right">


            <li><%= link_to "Users", '#' %></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", '#' %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Log out", forms_new_url%>
                </li>
              </ul>
            </li>


      </ul>
    </nav>
  </div>
<%end%>

app/views/forms/new.html.erb
<!DOCTYPE html>
<html>
<style>
body {
background-image: url("https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcS2FvhWnqdGrNmK2nrquFHZLrP3hYPUbSVOrM8znbvN0wOrck-ff1TbeMU");
background-repeat: no-repeat;
background-size: 200% 200%;
}

textarea {
  width: 15%;
  heigth:35;
}

input[type=submit] {
  width: 10%;
  background-color: #4CAF50;
  color: white;
  padding: 14px 20px;
  margin: 8px 0;
  border: none;
  border-radius: 4px;
  cursor: pointer;
}


input[type=submit]:hover {
  background-color: #45a049;
}
</style>

<%= form_for :form, url: forms_path do |f| %>


    <%= form_for @form do |f| %>
        <% if @form.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(@form.errors.count, "error") %> prohibited
                this Form from being saved:</h2>
              <ul>
                <% @form.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li><br><br>
                <% end %>
              </ul>
            </div>
        <% end %>



    <marquee direction="right"><i><h1 style="color:orangered;">Get Registered and Enjoy Learing</h1></marquee>
    <body style="background-color:powderblue;">
    <p><h3><i>Welcome</i></h3></p>
    <p></p>
<center>
    <p>
      <i>Firstname</i><br>
      <%= f.text_field :firstname %>

    </p>
    <p>
      <i> Lastname</i><br>
      <%= f.text_field :lastname %>
    </p>
    <p>
      <i> Email</i><br>
      <%= f.text_field :email %>
    </p>

    <p>
      <i> Password</i><br>
      <%= f.password_field :password %>


    <p>
     <i> Address</i><br>
      <%= f.text_area :address %>
    </p>

    <p>
      <%= f.submit :signup %>

    </p>

<% end %>
<% end %>


<i><%= link_to 'Log_in', login_path %></i>
</center>
<% if flash[:notice] %>
    <div class="notice"><%= flash[:notice] %></div>
<% end %>
</html>

app/views/forms/show.html.erb
<body style="background-color:orange;">
<p>
  <strong>Firstname:</strong>
  <%= @form.firstname %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @form.lastname %>
</p>
<strong>Email:</strong>
<%= @form.email %>
</p>
<strong>password:</strong>
<%= @form.password %>
</p>
<strong>Address:</strong>
<%= @form.address%>
</p>

<%= link_to 'Back', forms_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<style>
  body {
    margin: 0;
  }
  ul {
    list-style-type: none;
    margin: 0;
    padding: 0;
    overflow: hidden;
    background-color: orchid;
  }

  li {
    float: left;
  }

  li a {
    display: block;
    color: white;
    text-align: center;
    padding: 14px 16px;
    text-decoration: none;
  }

  li a:hover {
    background-color: #111;
  }


  li a.active {
    background-color: #4CAF50;
    color: white;
  }

  li a:hover:not(.active) {
    background-color: #555;
    color: white;
  }
</style>
  <head>
    <title>Myapp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="container">

      <nav>
        <ul class="nav navbar-nav navbar-right">
          <li ><a href="#">Home</a></li>
          <li ><a href="#">News</a></li>
          <li ><a href="#">Contact</a></li>
          <li ><a href="#">About</a></li>
        </ul>
      </nav>

    <%= yield %>

          <%#= flash[:notice] %>


    </div>

  </body>
</html>

app/views/users/new.html.erb
<h1>Signup!</h1>

<%= form_for :user, url: '/users' do |f| %>

    Name: <%= f.text_field :name %><br><br>
    Email: <%= f.text_field :email %>
    Password: <%= f.password_field :password %>
    Password Confirmation: <%= f.password_field :password_confirmation %>
    <%= f.submit "Submit" %>
    <%= link_to 'Back', forms_path %>

<% end %>

app/views/welcome/index.html.erb
<h1>Welcome </h1>
<p>
</p>

<%= link_to 'Back', controller: 'forms', :action => "new" %>